/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.SE;

import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.ByteArrayOutputStream;
import java.io.File;
import javax.swing.JButton;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.imageio.ImageIO;
import javax.swing.JFileChooser;



/**
 *
 * @author saaen
 */
public class peces extends javax.swing.JFrame {

    /**
     * Creates new form peces
     */
    
    private int registroActual = 1;
    
    
    public peces() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
        this.setLocationRelativeTo(null);
        
        establecerIconoEnBoton(jButton1, "src/com/images/inicio.png", 40, 40);
        establecerIconoEnBoton(jButton2, "src/com/images/anterior.png", 40, 40);
        establecerIconoEnBoton(jButton3, "src/com/images/siguiente.png", 40, 40);
        establecerIconoEnBoton(jButton4, "src/com/images/final.png", 40, 40);
        establecerIconoEnBoton(jButton5, "src/com/images/nuevo.png", 40, 40);
        establecerIconoEnBoton(jButton6, "src/com/images/grabar.png", 40, 40);
        establecerIconoEnBoton(jButton7, "src/com/images/cancelar.png", 40, 40);
        establecerIconoEnBoton(jButton8, "src/com/images/modificar.png", 40, 40);
        establecerIconoEnBoton(jButton9, "src/com/images/borrar.png", 40, 40);
        establecerIconoEnBoton(jButton10, "src/com/images/consultar.png", 40, 40);
        establecerIconoEnBoton(jButton11, "src/com/images/salir.png", 40, 40);
        establecerIconoEnBoton(jButton12, "src/com/images/imagen.png", 40, 40);
        
        
        ImageIcon logoAcuario = new ImageIcon ("src/com/images/acuario.png");
        ImageIcon acuario = new ImageIcon (logoAcuario.getImage().getScaledInstance(jLabel4.getWidth(), jLabel4.getHeight(), Image.SCALE_DEFAULT));
        jLabel4.setIcon(acuario);
        
        jTextField1.setEditable(false);
        jTextArea1.setEditable(false);
        
        jButton12.setEnabled(false);
        jButton6.setEnabled(false);
        jButton7.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton12 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Roboto Black", 0, 70)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 204));
        jLabel3.setText("\"DATOS DE PECES\"");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(663, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(652, 652, 652))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(jLabel3)
                .addContainerGap(71, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1920, 220));

        jPanel3.setBackground(new java.awt.Color(102, 102, 102));

        jButton1.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        jButton1.setText("INICIO");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        jButton2.setText("ANTERIOR");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        jButton3.setText("SIGUIENTE");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        jButton4.setText("FINAL");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        jButton5.setText("NUEVO");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });

        jButton6.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        jButton6.setText("GRABAR");
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton6MouseClicked(evt);
            }
        });

        jButton7.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        jButton7.setText("CANCELAR");
        jButton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton7MouseClicked(evt);
            }
        });

        jButton8.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        jButton8.setText("MODIFICAR");
        jButton8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton8MouseClicked(evt);
            }
        });

        jButton9.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        jButton9.setText("BORRAR");
        jButton9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton9MouseClicked(evt);
            }
        });

        jButton10.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        jButton10.setText("CONSULTAR");
        jButton10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton10MouseClicked(evt);
            }
        });

        jButton11.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        jButton11.setText("SALIR");
        jButton11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton11MouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        jLabel1.setText("Nombre del pez");

        jTextField1.setFont(new java.awt.Font("Roboto", 0, 36)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        jLabel2.setText("Descripción");

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Roboto", 0, 36)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setBorder(null);
        jScrollPane1.setViewportView(jTextArea1);

        jButton12.setFont(new java.awt.Font("Roboto", 1, 36)); // NOI18N
        jButton12.setText("IMAGEN");
        jButton12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton12MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(494, 494, 494)
                        .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(186, 186, 186)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(152, 152, 152))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(444, 444, 444)
                                .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPane1)
                                    .addComponent(jTextField1))))
                        .addGap(217, 217, 217)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(138, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextField1))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(364, 364, 364))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton4)
                    .addComponent(jButton3))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5)
                    .addComponent(jButton6)
                    .addComponent(jButton7)
                    .addComponent(jButton8)
                    .addComponent(jButton9))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton10)
                    .addComponent(jButton11))
                .addGap(113, 113, 113))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 1920, 860));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
       ConexionDB conexionDB = new ConexionDB();

        try {
            // Obtener la conexión a la base de datos
            Connection connection = conexionDB.obtenerConexion();

            // Preparar una consulta SQL para seleccionar el primer registro
            String sql = "SELECT nombre_objeto, descripcion, imagen FROM objeto LIMIT 1";
            PreparedStatement statement = connection.prepareStatement(sql);

            // Ejecutar la consulta
            ResultSet result = statement.executeQuery();

            // Verificar si hay un resultado
            if (result.next()) {
                // Obtener los datos del registro
                String nombre = result.getString("nombre_objeto");
                String descripcion = result.getString("descripcion");
                byte[] imagenBytes = result.getBytes("imagen");

                // Mostrar los datos en los componentes de la interfaz
                jTextField1.setText(nombre);
                jTextArea1.setText(descripcion);

                // Convertir el arreglo de bytes de la imagen a un ImageIcon
                ImageIcon imagenIcon = new ImageIcon(imagenBytes);

                // Escalar la imagen para que se ajuste al tamaño del jLabel4
                Image imagen = imagenIcon.getImage().getScaledInstance(jLabel4.getWidth(), jLabel4.getHeight(), Image.SCALE_SMOOTH);

                // Crear un nuevo ImageIcon con la imagen escalada y mostrarlo en jLabel4
                ImageIcon imagenEscalada = new ImageIcon(imagen);
                jLabel4.setIcon(imagenEscalada);
                registroActual = obtenerCantidadRegistros()/obtenerCantidadRegistros();
            } else {
                JOptionPane.showMessageDialog(this, "No se encontraron registros.");
            }
        } catch (Exception e) {
            //JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
            System.out.println("Error:" + e.getMessage());
        } finally {
            // Cerrar la conexión
            conexionDB.cerrarConexion();
        }
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton11MouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        experto j1 = new experto();
        j1.setVisible(true);
    }//GEN-LAST:event_jButton11MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
         ConexionDB conexionDB = new ConexionDB();

        try {
            // Verificar si estamos en el primer registro (registroActual igual a 1)
            if (registroActual > 1) {
                // Obtener la conexión a la base de datos
                Connection connection = conexionDB.obtenerConexion();

                // Preparar una consulta SQL para seleccionar el registro anterior
                String sql = "SELECT nombre_objeto, descripcion, imagen FROM objeto LIMIT 1 OFFSET " + (registroActual - 2);
                PreparedStatement statement = connection.prepareStatement(sql);

                // Ejecutar la consulta
                ResultSet result = statement.executeQuery();

                // Verificar si hay un resultado
                if (result.next()) {
                    // Obtener los datos del registro
                    String nombre = result.getString("nombre_objeto");
                    String descripcion = result.getString("descripcion");
                    byte[] imagenBytes = result.getBytes("imagen");

                    // Mostrar los datos en los componentes de la interfaz
                    jTextField1.setText(nombre);
                    jTextArea1.setText(descripcion);

                    // Decrementar el registro actual
                    registroActual--;

                    // Convertir el arreglo de bytes de la imagen a un ImageIcon
                    ImageIcon imagenIcon = new ImageIcon(imagenBytes);

                    // Escalar la imagen para que se ajuste al tamaño del jLabel4
                    Image imagen = imagenIcon.getImage().getScaledInstance(jLabel4.getWidth(), jLabel4.getHeight(), Image.SCALE_SMOOTH);

                    // Crear un nuevo ImageIcon con la imagen escalada y mostrarlo en jLabel4
                    ImageIcon imagenEscalada = new ImageIcon(imagen);
                    jLabel4.setIcon(imagenEscalada);
                }
            } else {
                JOptionPane.showMessageDialog(this, "No hay registros anteriores.");
            }
        } catch (Exception e) {
            System.out.println("Error: " + e.getMessage());
        } finally {
            // Cerrar la conexión
            conexionDB.cerrarConexion();
        }
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        // TODO add your handling code here:
        ConexionDB conexionDB = new ConexionDB();
        try {
            // Obtener la conexión a la base de datos
            Connection connection = conexionDB.obtenerConexion();

            // Preparar una consulta SQL para seleccionar el siguiente registro
            String sql = "SELECT nombre_objeto, descripcion, imagen FROM objeto LIMIT 1 OFFSET " + registroActual;
            PreparedStatement statement = connection.prepareStatement(sql);

            // Ejecutar la consulta
            ResultSet result = statement.executeQuery();

            // Verificar si hay un resultado
            if (result.next()) {
                // Obtener los datos del registro
                String nombre = result.getString("nombre_objeto");
                String descripcion = result.getString("descripcion");
                byte[] imagenBytes = result.getBytes("imagen");

                // Mostrar los datos en los componentes de la interfaz
                jTextField1.setText(nombre);
                jTextArea1.setText(descripcion);

                // Incrementar el registro actual
                registroActual++;

                // Convertir el arreglo de bytes de la imagen a un ImageIcon
                ImageIcon imagenIcon = new ImageIcon(imagenBytes);

                // Escalar la imagen para que se ajuste al tamaño del jLabel4
                Image imagen = imagenIcon.getImage().getScaledInstance(jLabel4.getWidth(), jLabel4.getHeight(), Image.SCALE_SMOOTH);

                // Crear un nuevo ImageIcon con la imagen escalada y mostrarlo en jLabel4
                ImageIcon imagenEscalada = new ImageIcon(imagen);
                jLabel4.setIcon(imagenEscalada);
            } else {
                JOptionPane.showMessageDialog(this, "No hay más registros.");
            }
        } catch (Exception e) {
            System.out.println("Error: " + e.getMessage());
        } finally {
            // Cerrar la conexión
            conexionDB.cerrarConexion();
        }
    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        // TODO add your handling code here:
         ConexionDB conexionDB = new ConexionDB();
        try {
            // Obtener la conexión a la base de datos
            Connection connection = conexionDB.obtenerConexion();

            // Preparar una consulta SQL para seleccionar el último registro
            String sql = "SELECT nombre_objeto, descripcion, imagen FROM objeto ORDER BY id_objeto DESC LIMIT 1";
            PreparedStatement statement = connection.prepareStatement(sql);

            // Ejecutar la consulta
            ResultSet result = statement.executeQuery();

            // Verificar si hay un resultado
            if (result.next()) {
                // Obtener los datos del registro
                String nombre = result.getString("nombre_objeto");
                String descripcion = result.getString("descripcion");
                byte[] imagenBytes = result.getBytes("imagen");

                // Mostrar los datos en los componentes de la interfaz
                jTextField1.setText(nombre);
                jTextArea1.setText(descripcion);

                // Convertir el arreglo de bytes de la imagen a un ImageIcon
                ImageIcon imagenIcon = new ImageIcon(imagenBytes);

                // Escalar la imagen para que se ajuste al tamaño del jLabel4
                Image imagen = imagenIcon.getImage().getScaledInstance(jLabel4.getWidth(), jLabel4.getHeight(), Image.SCALE_SMOOTH);

                // Crear un nuevo ImageIcon con la imagen escalada y mostrarlo en jLabel4
                ImageIcon imagenEscalada = new ImageIcon(imagen);
                jLabel4.setIcon(imagenEscalada);
                
                registroActual = obtenerCantidadRegistros();
            } else {
                JOptionPane.showMessageDialog(this, "No hay registros en la base de datos.");
            }
        } catch (Exception e) {
            System.out.println("Error: " + e.getMessage());
        } finally {
            // Cerrar la conexión
            conexionDB.cerrarConexion();
        }
    }//GEN-LAST:event_jButton4MouseClicked

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
        // TODO add your handling code here:
        jTextField1.setEditable(true);
        jTextArea1.setEditable(true);
        jButton6.setEnabled(true);
        jButton7.setEnabled(true);
        jButton12.setEnabled(true);
    }//GEN-LAST:event_jButton5MouseClicked

    private void jButton12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton12MouseClicked
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        int result = fileChooser.showOpenDialog(this);

        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fileChooser.getSelectedFile();
            ImageIcon icon = new ImageIcon(selectedFile.getAbsolutePath());

            // Escalar la imagen para que se ajuste al tamaño del jLabel4
            Image imagen = icon.getImage().getScaledInstance(jLabel4.getWidth(), jLabel4.getHeight(), Image.SCALE_SMOOTH);
            icon = new ImageIcon(imagen);
            jLabel4.setIcon(icon);
        }
    }//GEN-LAST:event_jButton12MouseClicked

    private void jButton6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseClicked
        // TODO add your handling code here:                                
        ConexionDB conexionDB = new ConexionDB();
        try {
            // Obtener la conexión a la base de datos
            Connection connection = conexionDB.obtenerConexion();

            // Obtener el nombre y descripción ingresados por el usuario
            String nombre = jTextField1.getText();
            String descripcion = jTextArea1.getText();

            // Verificar que se haya ingresado un nombre y una descripción
            if (nombre.isEmpty() || descripcion.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Por favor, ingrese un nombre y una descripción.");
                return; // Salir si falta información
            }

            // Obtener la imagen actualmente mostrada en el jLabel4
            ImageIcon icon = (ImageIcon) jLabel4.getIcon();
            Image imagen = icon.getImage();

            if (imagen != null) {
                // Convertir la imagen a un objeto BufferedImage
                BufferedImage bufferedImage = new BufferedImage(imagen.getWidth(null), imagen.getHeight(null), BufferedImage.TYPE_INT_RGB);
                Graphics2D g = bufferedImage.createGraphics();
                g.drawImage(imagen, 0, 0, null);
                g.dispose();

                // Convertir el BufferedImage a un arreglo de bytes (en formato JPEG en este ejemplo)
                ByteArrayOutputStream baos = new ByteArrayOutputStream();
                ImageIO.write(bufferedImage, "jpg", baos);
                byte[] imagenBytes = baos.toByteArray();

                // Preparar una consulta SQL para verificar si el registro ya existe
                String verificaExistenciaSql = "SELECT id_objeto FROM objeto WHERE nombre_objeto = ?";
                PreparedStatement verificaExistenciaStatement = connection.prepareStatement(verificaExistenciaSql);
                verificaExistenciaStatement.setString(1, nombre);

                ResultSet resultSet = verificaExistenciaStatement.executeQuery();

                if (resultSet.next()) {
                    // El registro ya existe, actualízalo

                    // Obtener el ID del registro existente
                    int id = resultSet.getInt("id_objeto");

                    // Preparar una consulta SQL para actualizar el registro
                    String actualizaRegistroSql = "UPDATE objeto SET descripcion = ?, imagen = ? WHERE id_objeto = ?";
                    PreparedStatement actualizaRegistroStatement = connection.prepareStatement(actualizaRegistroSql);

                    // Establecer los parámetros en la consulta de actualización
                    actualizaRegistroStatement.setString(1, descripcion);
                    actualizaRegistroStatement.setBytes(2, imagenBytes);
                    actualizaRegistroStatement.setInt(3, id);

                    int filasAfectadas = actualizaRegistroStatement.executeUpdate();

                    if (filasAfectadas > 0) {
                        JOptionPane.showMessageDialog(this, "Registro actualizado con éxito.");
                        ImageIcon logoAcuario = new ImageIcon ("src/com/images/acuario.png");
                        ImageIcon acuario = new ImageIcon (logoAcuario.getImage().getScaledInstance(jLabel4.getWidth(), jLabel4.getHeight(), Image.SCALE_DEFAULT));
                        jLabel4.setIcon(acuario);

                        jTextField1.setText("");
                        jTextArea1.setText("");
                        jButton12.setEnabled(false);
                        jButton6.setEnabled(false);
                        jButton7.setEnabled(false);
                    } else {
                        JOptionPane.showMessageDialog(this, "Error al actualizar el registro.");
                    }
                } else {
                    // El registro no existe, inserta uno nuevo

                    // Preparar una consulta SQL para insertar el nuevo registro
                    String insertaRegistroSql = "INSERT INTO objeto (nombre_objeto, descripcion, imagen) VALUES (?, ?, ?)";
                    PreparedStatement insertaRegistroStatement = connection.prepareStatement(insertaRegistroSql);

                    // Establecer los parámetros en la consulta de inserción
                    insertaRegistroStatement.setString(1, nombre);
                    insertaRegistroStatement.setString(2, descripcion);
                    insertaRegistroStatement.setBytes(3, imagenBytes);

                    int filasAfectadas = insertaRegistroStatement.executeUpdate();

                    if (filasAfectadas > 0) {
                        JOptionPane.showMessageDialog(this, "Registro insertado con éxito.");
                        ImageIcon logoAcuario = new ImageIcon ("src/com/images/acuario.png");
                        ImageIcon acuario = new ImageIcon (logoAcuario.getImage().getScaledInstance(jLabel4.getWidth(), jLabel4.getHeight(), Image.SCALE_DEFAULT));
                        jLabel4.setIcon(acuario);

                        jTextField1.setText("");
                        jTextArea1.setText("");
                        jButton12.setEnabled(false);
                        jButton6.setEnabled(false);
                        jButton7.setEnabled(false);
                    } else {
                        JOptionPane.showMessageDialog(this, "Error al insertar el registro.");
                    }
                }
            } else {
                JOptionPane.showMessageDialog(this, "No se ha cargado una imagen.");
            }

            // Cerrar la conexión a la base de datos
            conexionDB.cerrarConexion();

        } catch (Exception e) {
            System.out.println("Error al guardar o actualizar en la base de datos: " + e.getMessage());
        }
        

    }//GEN-LAST:event_jButton6MouseClicked

    private void jButton7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton7MouseClicked
        // TODO add your handling code here:
        ImageIcon logoAcuario = new ImageIcon ("src/com/images/acuario.png");
        ImageIcon acuario = new ImageIcon (logoAcuario.getImage().getScaledInstance(jLabel4.getWidth(), jLabel4.getHeight(), Image.SCALE_DEFAULT));
        jLabel4.setIcon(acuario);
        
        jTextField1.setText("");
        jTextArea1.setText("");
        jButton12.setEnabled(false);
        jButton6.setEnabled(false);
        jButton7.setEnabled(false);
    }//GEN-LAST:event_jButton7MouseClicked

    private void jButton8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton8MouseClicked
        // TODO add your handling code here:
        jTextField1.setEditable(true);
        jTextArea1.setEditable(true);
        jButton6.setEnabled(true);
        jButton7.setEnabled(true);
        jButton12.setEnabled(true);
        
        ConexionDB conexionDB = new ConexionDB();

        try {
            // Obtener la conexión a la base de datos
            Connection connection = conexionDB.obtenerConexion();

            // Obtener el nombre y descripción ingresados por el usuario
            String nombre = jTextField1.getText();
            String descripcion = jTextArea1.getText();

            // Verificar que se haya ingresado un nombre y una descripción
            if (nombre.isEmpty() || descripcion.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Por favor, ingrese un nombre y una descripción.");
                return; // Salir si falta información
            }

            // Obtener la imagen actualmente mostrada en el jLabel4
            ImageIcon icon = (ImageIcon) jLabel4.getIcon();
            Image imagen = icon.getImage();

            // Convertir la imagen a un objeto BufferedImage
            BufferedImage bufferedImage = new BufferedImage(imagen.getWidth(null), imagen.getHeight(null), BufferedImage.TYPE_INT_RGB);
            Graphics2D g = bufferedImage.createGraphics();
            g.drawImage(imagen, 0, 0, null);
            g.dispose();

            // Convertir el BufferedImage a un arreglo de bytes (en formato JPEG en este ejemplo)
            ByteArrayOutputStream baos = new ByteArrayOutputStream();
            ImageIO.write(bufferedImage, "jpeg", baos);
            byte[] imagenBytes = baos.toByteArray();

            // Preparar una consulta SQL para actualizar los datos en la base de datos
            String sql = "UPDATE objeto SET nombre_objeto = ?, descripcion = ?, imagen = ? WHERE id_objeto = ?"; // Asume que existe un campo ID para identificar el registro a actualizar
            PreparedStatement statement = connection.prepareStatement(sql);

            // Establecer los parámetros en la consulta
            statement.setString(1, nombre);
            statement.setString(2, descripcion);
            statement.setBytes(3, imagenBytes);

            // Ejecutar la consulta para actualizar el registro
            int filasAfectadas = statement.executeUpdate();

            if (filasAfectadas > 0) {
                jButton12.setEnabled(false);
                jButton6.setEnabled(false);
                jButton7.setEnabled(false);
                JOptionPane.showMessageDialog(this, "Registro actualizado con éxito.");
            } else {
                JOptionPane.showMessageDialog(this, "Error al actualizar el registro.");
            }

            // Cerrar la conexión a la base de datos
            conexionDB.cerrarConexion();

        } catch (Exception e) {
            System.out.println("Error al actualizar en la base de datos: " + e.getMessage());
        }
    }//GEN-LAST:event_jButton8MouseClicked

    private void jButton9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton9MouseClicked
        // TODO add your handling code here:
        // Paso 1: Solicitar al usuario el nombre del pez a eliminar
        String nombrePez = JOptionPane.showInputDialog(this, "Ingrese el nombre del pez que desea eliminar:");

        if (nombrePez != null && !nombrePez.isEmpty()) { // Verificar que se haya ingresado un nombre

            ConexionDB conexionDB = new ConexionDB();
            try {
                // Obtener la conexión a la base de datos
                Connection connection = conexionDB.obtenerConexion();

                // Preparar una consulta SQL para verificar si el pez existe y obtener el id_objeto
                String verificaExistenciaSql = "SELECT id_objeto, descripcion FROM objeto WHERE nombre_objeto = ?";
                PreparedStatement verificaExistenciaStatement = connection.prepareStatement(verificaExistenciaSql);
                verificaExistenciaStatement.setString(1, nombrePez);

                ResultSet resultSet = verificaExistenciaStatement.executeQuery();

                if (resultSet.next()) {
                    // Obtener el id_objeto y la descripción del pez
                    int idPez = resultSet.getInt("id_objeto");
                    String descripcionPez = resultSet.getString("descripcion");

                    // Paso 3: Mostrar los datos del pez, incluido el id_objeto, y preguntar si el usuario está seguro de eliminarlo
                    int respuesta = JOptionPane.showConfirmDialog(this, "ID: " + idPez + "\nNombre: " + nombrePez + "\nDescripción: " + descripcionPez + "\n¿Está seguro de eliminar este registro?", "Confirmar eliminación", JOptionPane.YES_NO_OPTION);

                    if (respuesta == JOptionPane.YES_OPTION) { // Si el usuario confirma la eliminación
                        // Paso 4: Ejecutar la consulta SQL para eliminar el registro
                        String eliminaRegistroSql = "DELETE FROM objeto WHERE nombre_objeto = ?";
                        PreparedStatement eliminaRegistroStatement = connection.prepareStatement(eliminaRegistroSql);
                        eliminaRegistroStatement.setString(1, nombrePez);
                        int filasAfectadas = eliminaRegistroStatement.executeUpdate();

                        if (filasAfectadas > 0) {
                            JOptionPane.showMessageDialog(this, "Registro eliminado con éxito.");
                        } else {
                            JOptionPane.showMessageDialog(this, "Error al eliminar el registro.");
                        }
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "El pez con el nombre '" + nombrePez + "' no existe en la base de datos.");
                }

                // Cerrar la conexión a la base de datos
                conexionDB.cerrarConexion();

            } catch (Exception e) {
                System.out.println("Error al eliminar en la base de datos: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_jButton9MouseClicked

    private void jButton10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton10MouseClicked
        // TODO add your handling code here:
        String nombrePez = JOptionPane.showInputDialog(this, "Ingrese el nombre del pez que desea consultar:");
        if (nombrePez != null && !nombrePez.isEmpty()) { // Verificar que se haya ingresado un nombre

            ConexionDB conexionDB = new ConexionDB();
            try {
                // Obtener la conexión a la base de datos
                Connection connection = conexionDB.obtenerConexion();

                // Preparar una consulta SQL para verificar si el pez existe y obtener los datos
                String consultaSql = "SELECT descripcion, imagen FROM objeto WHERE nombre_objeto = ?";
                PreparedStatement consultaStatement = connection.prepareStatement(consultaSql);
                consultaStatement.setString(1, nombrePez);

                ResultSet resultSet = consultaStatement.executeQuery();

                if (resultSet.next()) {
                    // Paso 3: Mostrar los datos del pez en los elementos de la interfaz de usuario
                    String descripcionPez = resultSet.getString("descripcion");
                    byte[] imagenBytes = resultSet.getBytes("imagen");

                    jTextField1.setText(nombrePez);
                    jTextArea1.setText(descripcionPez);

                    if (imagenBytes != null) {
                        // Convertir la imagen de bytes a ImageIcon
                        ImageIcon imagenIcon = new ImageIcon(imagenBytes);
                        Image imagen = imagenIcon.getImage();

                        // Escalar la imagen al tamaño del jLabel4
                        int anchoLabel = jLabel4.getWidth();
                        int altoLabel = jLabel4.getHeight();
                        Image imagenEscalada = imagen.getScaledInstance(anchoLabel, altoLabel, Image.SCALE_SMOOTH);

                        // Crear un nuevo ImageIcon con la imagen escalada y establecerlo en jLabel4
                        ImageIcon imagenEscaladaIcon = new ImageIcon(imagenEscalada);
                        jLabel4.setIcon(imagenEscaladaIcon);
                    } else {
                        // Si no hay imagen en la base de datos, establece jLabel4 en nulo o muestra un mensaje de error
                        jLabel4.setIcon(null);
                        JOptionPane.showMessageDialog(this, "El pez no tiene una imagen en la base de datos.");
                    }
                } else {
                    // Mostrar un mensaje si el pez no existe en la base de datos
                    JOptionPane.showMessageDialog(this, "El pez con el nombre '" + nombrePez + "' no existe en la base de datos.");
                    jTextField1.setText(""); // Borrar el nombre en jTextField1
                    jTextArea1.setText(""); // Borrar la descripción en jTextArea1
                    jLabel4.setIcon(null); // Borrar la imagen en jLabel4
                }

                // Cerrar la conexión a la base de datos
                conexionDB.cerrarConexion();

            } catch (Exception e) {
                System.out.println("Error al consultar en la base de datos: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_jButton10MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(peces.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(peces.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(peces.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(peces.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new peces().setVisible(true);
            }
        });
    }
    
    public int obtenerCantidadRegistros() {
        int totalRegistros = 0;
        ConexionDB conexionDB = new ConexionDB();
        try {
            // Obtener la conexión a la base de datos
            Connection connection = conexionDB.obtenerConexion();

            // Preparar una consulta SQL para contar la cantidad de registros
            String countQuery = "SELECT COUNT(*) AS total_registros FROM objeto";
            PreparedStatement countStatement = connection.prepareStatement(countQuery);
            ResultSet countResult = countStatement.executeQuery();

            if (countResult.next()) {
                totalRegistros = countResult.getInt("total_registros");
            }
        } catch (Exception e) {
            System.out.println("Error al obtener la cantidad de registros: " + e.getMessage());
        } finally {
            // Cerrar la conexión
            conexionDB.cerrarConexion();
        }

        return totalRegistros;
    }

    
    public void establecerIconoEnBoton(JButton boton, String rutaIcono, int ancho, int alto) {
        ImageIcon icono = new ImageIcon(rutaIcono);
        Image imagen = icono.getImage().getScaledInstance(ancho, alto, Image.SCALE_SMOOTH); // Puedes cambiar SCALE_SMOOTH a otro método de escala si lo prefieres
        ImageIcon iconoEscalado = new ImageIcon(imagen);
        boton.setIcon(iconoEscalado);
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
